name: HelloWorld
main: com.dadahasa.mc.Main
version: 1.2
commands:
   join:
      description: /join ctk
      usage: /<command>
   hub:
      description: Goes to the hub.
      usage: /<command>
   forcestart:
      description: Starts the game.
      usage: /<command>
   stopspam:
      description: Stops spam.
      usage: /<command>